[package]
name = "sixtyfps-rendering-backend-testing"
version = "0.1.4"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
description = "OpenGL rendering backend for SixtyFPS"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"
publish = false

[lib]
path = "lib.rs"

[dependencies]
sixtyfps-corelib = { version = "=0.1.4", path = "../../corelib" }
image = { version = "0.23.14", default-features = false, features = ["png"], optiona = "true" }
weak-table = "0.3"
